<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '65a923fd66f9b2256c8e78996b1f1d9b',
  'DATABASE_URL' => 'mysql://symfony:symfony@database:3306/code_test?serverVersion=8.0',
  'GITHUB_TOKEN' => 'xyz',
);
