#index:
#    path: /
#    controller: App\Controller\DefaultController::index
test_fetch:
    path: /test
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\TestController::index